// lib/core/mock_data.dart

// ── USER PROFILE ─────────────────────────────────────────────────────────────
const kUserProfile = {
  'name': 'John Doe',
  'email': 'john.doe@securehome.app',
  'plan': 'Pro',
  'memberSince': '2023',
  'avatar': 'JD',
};

// ── CAMERAS ──────────────────────────────────────────────────────────────────
const kCameras = [
  {
    'id': 'pi_cam',
    'name': 'Pi Camera',
    'zone': 'Door',
    'status': 'online',
    'isOn': true,
    'alerts': 0,
    'recording': true,
    'nightVision': true,
    'motionDetection': true,
    'audioRecording': false,
    'personAlerts': true,
    'motionAlerts': true,
    'soundDetection': false,
    'videoQuality': '1080p',
    'storageLocation': 'Local',
    'continuousRecording': true,
    'ip': '',
    'firmware': 'v3.0',
    'battery': 100,
    'signal': 90,
    'thumb': '',
    'lastMotion': 'Live',
    'lastSeen': null,
    'isRecording': true,
    'ptzSupported': false,
    'privacyMask': false,
  },
  {
    'id': 'c1',
    'name': 'Front Door',
    'zone': 'Exterior',
    'status': 'online',
    'isOn': true,
    'alerts': 3,
    'recording': true,
    'nightVision': true,
    'motionDetection': true,
    'audioRecording': true,
    'personAlerts': true,
    'motionAlerts': true,
    'soundDetection': false,
    'videoQuality': '4K',
    'storageLocation': 'Cloud',
    'continuousRecording': true,
    'ip': '192.168.1.10',
    'firmware': 'v3.1.2',
    'battery': 88,
    'signal': 95,
    'thumb':
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    'lastMotion': '2 min ago',
    'lastSeen': null,
    'isRecording': false,
    'ptzSupported': true,
    'privacyMask': false,
  },
  {
    'id': 'c2',
    'name': 'Living Room',
    'zone': 'Interior',
    'status': 'online',
    'isOn': true,
    'alerts': 1,
    'recording': false,
    'nightVision': false,
    'motionDetection': true,
    'audioRecording': true,
    'personAlerts': false,
    'motionAlerts': true,
    'soundDetection': true,
    'videoQuality': '1080p',
    'storageLocation': 'Cloud',
    'continuousRecording': false,
    'ip': '192.168.1.11',
    'firmware': 'v3.1.2',
    'battery': 100,
    'signal': 88,
    'thumb':
        'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
    'lastMotion': '1 hr ago',
    'lastSeen': null,
    'isRecording': false,
    'ptzSupported': false,
    'privacyMask': false,
  },
  {
    'id': 'c3',
    'name': 'Backyard',
    'zone': 'Exterior',
    'status': 'online',
    'isOn': true,
    'alerts': 0,
    'recording': false,
    'nightVision': true,
    'motionDetection': true,
    'audioRecording': false,
    'personAlerts': true,
    'motionAlerts': true,
    'soundDetection': false,
    'videoQuality': '1080p',
    'storageLocation': 'Local',
    'continuousRecording': false,
    'ip': '192.168.1.12',
    'firmware': 'v3.0.8',
    'battery': 62,
    'signal': 72,
    'thumb':
        'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
    'lastMotion': '34 min ago',
    'lastSeen': null,
    'isRecording': false,
    'ptzSupported': false,
    'privacyMask': false,
  },
  {
    'id': 'c4',
    'name': 'Garage',
    'zone': 'Exterior',
    'status': 'offline',
    'isOn': false,
    'alerts': 0,
    'recording': false,
    'nightVision': false,
    'motionDetection': false,
    'audioRecording': false,
    'personAlerts': false,
    'motionAlerts': false,
    'soundDetection': false,
    'videoQuality': '1080p',
    'storageLocation': 'Local',
    'continuousRecording': false,
    'ip': '192.168.1.13',
    'firmware': 'v2.9.1',
    'battery': 8,
    'signal': 0,
    'thumb':
        'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80',
    'lastMotion': '5 hr ago',
    'lastSeen': '2024-10-26T10:00:00',
    'isRecording': false,
    'ptzSupported': false,
    'privacyMask': false,
  },
];

// ── ALERTS ───────────────────────────────────────────────────────────────────
const kAlerts = [
  {
    'id': 'a1',
    'type': 'person',
    'title': 'Person Detected',
    'subtitle': 'Someone approached your front door',
    'camera': 'Front Door',
    'time': '2 min ago',
    'isRead': false,
    'thumb':
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    'zone': 'Exterior',
    'severity': 'high',
    'clipId': 'r1',
    'timestamp': '2024-10-26T10:28:00',
  },
  {
    'id': 'a2',
    'type': 'motion',
    'title': 'Motion Detected',
    'subtitle': 'Movement detected in backyard',
    'camera': 'Backyard',
    'time': '18 min ago',
    'isRead': false,
    'thumb':
        'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    'zone': 'Exterior',
    'severity': 'medium',
    'clipId': 'r3',
    'timestamp': '2024-10-26T10:12:00',
  },
  {
    'id': 'a3',
    'type': 'person',
    'title': 'Person Detected',
    'subtitle': 'Person detected near garage',
    'camera': 'Backyard',
    'time': '34 min ago',
    'isRead': false,
    'thumb':
        'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    'zone': 'Exterior',
    'severity': 'high',
    'clipId': 'r3',
    'timestamp': '2024-10-25T10:00:00',
  },
  {
    'id': 'a4',
    'type': 'motion',
    'title': 'Motion in Living Room',
    'subtitle': 'Motion detected on indoor camera',
    'camera': 'Living Room',
    'time': '1 hr ago',
    'isRead': true,
    'thumb':
        'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80',
    'zone': 'Interior',
    'severity': 'low',
    'clipId': 'r4',
    'timestamp': '2024-10-25T09:30:00',
  },
  {
    'id': 'a5',
    'type': 'system',
    'title': 'Camera Offline',
    'subtitle': 'Garage camera lost connection',
    'camera': 'Garage',
    'time': '2 hr ago',
    'isRead': true,
    'thumb': null,
    'zone': 'Exterior',
    'severity': 'high',
    'clipId': null,
    'timestamp': '2024-10-25T08:30:00',
  },
  {
    'id': 'a6',
    'type': 'recording',
    'title': 'Recording Saved',
    'subtitle': 'New clip saved to cloud storage',
    'camera': 'Front Door',
    'time': '3 hr ago',
    'isRead': true,
    'thumb': null,
    'zone': 'Exterior',
    'severity': 'low',
    'clipId': 'r7',
    'timestamp': '2024-10-24T07:30:00',
  },
  {
    'id': 'a7',
    'type': 'motion',
    'title': 'Motion Detected',
    'subtitle': 'Activity outside front door',
    'camera': 'Front Door',
    'time': '5 hr ago',
    'isRead': true,
    'thumb':
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    'zone': 'Exterior',
    'severity': 'medium',
    'clipId': 'r5',
    'timestamp': '2024-10-24T05:30:00',
  },
];

// ── RECORDINGS (multi-day) ────────────────────────────────────────────────────
const kRecordings = [
  // Oct 26
  {
    'id': 'r1',
    'cameraId': 'c1',
    'camera': 'Front Door',
    'date': 'Oct 26, 10:30 AM',
    'duration': '2:15',
    'type': 'person',
    'thumb':
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    'zone': 'Exterior',
    'fileSize': '18.4 MB',
    'isFavourite': false,
    'isDownloaded': false,
    'alertId': 'a1',
    'timestamp': '2024-10-26T10:30:00'
  },
  {
    'id': 'r2',
    'cameraId': 'c1',
    'camera': 'Front Door',
    'date': 'Oct 26, 11:04 AM',
    'duration': '0:48',
    'type': 'motion',
    'thumb':
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    'zone': 'Exterior',
    'fileSize': '6.2 MB',
    'isFavourite': false,
    'isDownloaded': false,
    'alertId': 'a2',
    'timestamp': '2024-10-26T11:04:00'
  },
  {
    'id': 'r3',
    'cameraId': 'c3',
    'camera': 'Backyard',
    'date': 'Oct 26, 11:22 AM',
    'duration': '1:33',
    'type': 'motion',
    'thumb':
        'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    'zone': 'Exterior',
    'fileSize': '11.7 MB',
    'isFavourite': false,
    'isDownloaded': false,
    'alertId': null,
    'timestamp': '2024-10-26T11:22:00'
  },
  {
    'id': 'r4',
    'cameraId': 'c2',
    'camera': 'Living Room',
    'date': 'Oct 26, 12:01 PM',
    'duration': '3:02',
    'type': 'motion',
    'thumb':
        'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80',
    'zone': 'Interior',
    'fileSize': '23.1 MB',
    'isFavourite': true,
    'isDownloaded': false,
    'alertId': 'a4',
    'timestamp': '2024-10-26T12:01:00'
  },
  {
    'id': 'r5',
    'cameraId': 'c1',
    'camera': 'Front Door',
    'date': 'Oct 26, 01:15 PM',
    'duration': '1:07',
    'type': 'person',
    'thumb':
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    'zone': 'Exterior',
    'fileSize': '8.9 MB',
    'isFavourite': false,
    'isDownloaded': true,
    'alertId': 'a7',
    'timestamp': '2024-10-26T13:15:00'
  },
  {
    'id': 'r6',
    'cameraId': 'c3',
    'camera': 'Backyard',
    'date': 'Oct 26, 02:44 PM',
    'duration': '0:55',
    'type': 'motion',
    'thumb':
        'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    'zone': 'Exterior',
    'fileSize': '7.1 MB',
    'isFavourite': false,
    'isDownloaded': false,
    'alertId': null,
    'timestamp': '2024-10-26T14:44:00'
  },
  {
    'id': 'r7',
    'cameraId': 'c1',
    'camera': 'Front Door',
    'date': 'Oct 26, 03:30 PM',
    'duration': '2:41',
    'type': 'person',
    'thumb':
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    'zone': 'Exterior',
    'fileSize': '20.3 MB',
    'isFavourite': true,
    'isDownloaded': false,
    'alertId': 'a6',
    'timestamp': '2024-10-26T15:30:00'
  },
  {
    'id': 'r8',
    'cameraId': 'c2',
    'camera': 'Living Room',
    'date': 'Oct 26, 04:12 PM',
    'duration': '1:18',
    'type': 'motion',
    'thumb':
        'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80',
    'zone': 'Interior',
    'fileSize': '10.0 MB',
    'isFavourite': false,
    'isDownloaded': false,
    'alertId': null,
    'timestamp': '2024-10-26T16:12:00'
  },
  {
    'id': 'r9',
    'cameraId': 'c3',
    'camera': 'Backyard',
    'date': 'Oct 26, 05:03 PM',
    'duration': '0:37',
    'type': 'motion',
    'thumb':
        'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    'zone': 'Exterior',
    'fileSize': '4.8 MB',
    'isFavourite': false,
    'isDownloaded': false,
    'alertId': null,
    'timestamp': '2024-10-26T17:03:00'
  },
  // Oct 25
  {
    'id': 'r10',
    'cameraId': 'c1',
    'camera': 'Front Door',
    'date': 'Oct 25, 09:10 AM',
    'duration': '1:22',
    'type': 'person',
    'thumb':
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    'zone': 'Exterior',
    'fileSize': '10.5 MB',
    'isFavourite': false,
    'isDownloaded': false,
    'alertId': null,
    'timestamp': '2024-10-25T09:10:00'
  },
  {
    'id': 'r11',
    'cameraId': 'c2',
    'camera': 'Living Room',
    'date': 'Oct 25, 10:45 AM',
    'duration': '2:50',
    'type': 'motion',
    'thumb':
        'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80',
    'zone': 'Interior',
    'fileSize': '21.6 MB',
    'isFavourite': false,
    'isDownloaded': false,
    'alertId': null,
    'timestamp': '2024-10-25T10:45:00'
  },
  {
    'id': 'r12',
    'cameraId': 'c3',
    'camera': 'Backyard',
    'date': 'Oct 25, 02:30 PM',
    'duration': '0:41',
    'type': 'motion',
    'thumb':
        'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    'zone': 'Exterior',
    'fileSize': '5.3 MB',
    'isFavourite': false,
    'isDownloaded': false,
    'alertId': null,
    'timestamp': '2024-10-25T14:30:00'
  },
  // Oct 24
  {
    'id': 'r13',
    'cameraId': 'c1',
    'camera': 'Front Door',
    'date': 'Oct 24, 08:00 AM',
    'duration': '3:10',
    'type': 'person',
    'thumb':
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    'zone': 'Exterior',
    'fileSize': '24.2 MB',
    'isFavourite': true,
    'isDownloaded': false,
    'alertId': null,
    'timestamp': '2024-10-24T08:00:00'
  },
  {
    'id': 'r14',
    'cameraId': 'c2',
    'camera': 'Living Room',
    'date': 'Oct 24, 11:20 AM',
    'duration': '1:05',
    'type': 'motion',
    'thumb':
        'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80',
    'zone': 'Interior',
    'fileSize': '8.1 MB',
    'isFavourite': false,
    'isDownloaded': false,
    'alertId': null,
    'timestamp': '2024-10-24T11:20:00'
  },
  // Oct 23
  {
    'id': 'r15',
    'cameraId': 'c3',
    'camera': 'Backyard',
    'date': 'Oct 23, 06:55 PM',
    'duration': '2:05',
    'type': 'person',
    'thumb':
        'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80',
    'zone': 'Exterior',
    'fileSize': '16.0 MB',
    'isFavourite': false,
    'isDownloaded': false,
    'alertId': null,
    'timestamp': '2024-10-23T18:55:00'
  },
];
